version: '3'
services:
    proxy:
        image: proxy:latest
        ports:
            - 443:443
        deploy:
            replicas: 4

    django:
        image: django-app:latest
        deploy:
            replicas: 4
